services:

  postgres:
    image: postgres:16
    container_name: gym_pass_database
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
    - gym_pass_network

  redis:
    image: redis:7
    container_name: gym_pass_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
    - gym_pass_network

  traefik:
    image: traefik:v3.0
    container_name: gym_pass_traefik
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.email=gym.pass.project@outlook.pt"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"

  backend:
    #build: ./services
    image: ricardo5ro/gym-pass-backend:${IMAGE_TAG}
    container_name: gym_pass_backend
    depends_on:
      - postgres
      - redis
    expose:
      - "8080"
    environment:
      DB_URL: ${DB_URL}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
    - gym_pass_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`api-gym-pass.site`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certresolver=letsencrypt"
      - "traefik.http.services.backend.loadbalancer.server.port=3000"

  #nginx:
  #  image: nginx:latest
  #  container_name: gym_pass_nginx
  #  ports:
  #    - "80:80"
  #  volumes:
  #    - ./nginx.conf:/etc/nginx/nginx.conf
  #  depends_on:
  #    - backend
  #  networks:
  #    - gym_pass_network

volumes:
  postgres_data:
  redis_data:

networks:
  gym_pass_network:
    driver: bridge