services:

  redis:
    image: redis:7
    restart: unless-stopped
    container_name: gym_pass_redis
    #ports:
    #  - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
    - gym_pass_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  backend:
    #build: ./services
    image: ricardo5ro/gym-pass-backend:${IMAGE_TAG}
    restart: always
    container_name: gym_pass_backend
    depends_on:
      #postgres:
      #  condition: service_healthy
      redis:
        condition: service_healthy
    expose:
      - "8080"
    environment:
      DB_URL: ${DB_URL}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      EXTERNAL_API_BASE_URL: ${EXTERNAL_API_BASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
    networks:
    - gym_pass_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 5s
      retries: 3

nginx:
    image: nginx:latest
    restart: unless-stopped
    container_name: gym_pass_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - gym_pass_network
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 5s
      retries: 3

  ### LEGACY
  #postgres:
  #  image: postgres:16
  #  restart: unless-stopped
  #  container_name: gym_pass_database
  #  environment:
  #    POSTGRES_DB: ${DB_NAME}
  #    POSTGRES_USER: ${DB_USERNAME}
  #    POSTGRES_PASSWORD: ${DB_PASSWORD}
  #  ports:
  #    - "5432:5432"
  #  volumes:
  #    - postgres_data:/var/lib/postgresql/data
  #  networks:
  #  - gym_pass_network
  #  healthcheck:
  #    test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
  #    interval: 10s
  #    timeout: 5s
  #    retries: 3

volumes:
  postgres_data:
  redis_data:

networks:
  gym_pass_network:
    driver: bridge