CREATE TABLE T_USER (
    ID UUID PRIMARY KEY,
    EXTERNAL_ID VARCHAR(255),
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    ROLE VARCHAR(50) NOT NULL,
    IS_IMPORTED BOOLEAN NOT NULL DEFAULT FALSE,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_users_email ON T_USER(EMAIL);
CREATE INDEX idx_users_external_id ON T_USER(EXTERNAL_ID);