CREATE TABLE T_GYM (
    ID BIGINT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    ADDRESS VARCHAR(500) NOT NULL,
    CITY VARCHAR(100) NOT NULL,
    STATE VARCHAR(50) NOT NULL,
    POSTAL_CODE VARCHAR(20) NOT NULL,
    COUNTRY VARCHAR(100) NOT NULL DEFAULT 'Portugal',
    PHONE VARCHAR(50),
    EMAIL VARCHAR(255),
    TIMEZONE VARCHAR(50) NOT NULL DEFAULT 'Europe/Lisbon',
    OPENING_TIME TIME,
    CLOSING_TIME TIME,
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    MAX_CAPACITY INTEGER,
    OWNER_ID BIGINT NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_gyms_owner FOREIGN KEY (OWNER_ID) REFERENCES T_USER(ID)
);

CREATE INDEX idx_gyms_owner_id ON T_GYM(OWNER_ID);
CREATE INDEX idx_gyms_is_active ON T_GYM(IS_ACTIVE);
CREATE INDEX idx_gyms_city ON T_GYM(CITY);
