CREATE TABLE T_MEMBERSHIPS (
    ID BIGINT PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    GYM_ID BIGINT NOT NULL,
    STATUS VARCHAR(50) NOT NULL,
    TIER VARCHAR(50) NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_memberships_user FOREIGN KEY (USER_ID) REFERENCES T_USER(ID),
    CONSTRAINT fk_memberships_gym FOREIGN KEY (GYM_ID) REFERENCES T_GYM(ID)
);

CREATE INDEX idx_memberships_user_id ON T_MEMBERSHIPS(USER_ID);
CREATE INDEX idx_memberships_external_id ON T_MEMBERSHIPS(EXTERNAL_ID);
CREATE INDEX idx_memberships_gym_id ON T_MEMBERSHIPS(GYM_ID);
CREATE INDEX idx_memberships_status ON T_MEMBERSHIPS(STATUS);
