CREATE SEQUENCE SEQ_USER START WITH 100001 INCREMENT BY 1;
CREATE SEQUENCE SEQ_GYM START WITH 100001 INCREMENT BY 1;
CREATE SEQUENCE SEQ_MEMBERSHIP START WITH 100001 INCREMENT BY 1;

UPDATE T_USER SET ID = NEXTVAL('SEQ_USER');
UPDATE T_GYM SET ID = NEXTVAL('SEQ_GYM');
UPDATE T_MEMBERSHIPS SET ID = NEXTVAL('SEQ_MEMBERSHIP');

SELECT SETVAL('SEQ_USER', (SELECT MAX(ID) FROM T_USER));
SELECT SETVAL('SEQ_GYM', (SELECT MAX(ID) FROM T_GYM));
SELECT SETVAL('SEQ_MEMBERSHIP', (SELECT MAX(ID) FROM T_MEMBERSHIPS));